v = input('Digite algo: ')
print(f'O tipo primitido desse valor é {type(v)}')
print(f'Só tem espaços? {v.isspace()}')
print(f'É um número? {v.isnumeric()}')
print(f'É um alfabético {v.isalpha()}')
print(f'É um alfanumérico? {v.isalnum()}')
print(f'Está em maiuscúlas? {v.isupper()}')
print(f'Está em minúsculas? {v.islower()}')
print(f'Está capitalizada? {v.istitle()}')
